Improve output and default config

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,6 +1,7 @@
 #!/bin/sh
 
-[ -f $HOME/.config/galley ] || { echo "missing '~/.config/galley'--maybe copy 'config-example'?"; exit 1; }
+[ -f $HOME/.config/galley ] || \
+    { echo "missing '~/.config/galley'--copy 'config-example'?"; exit 1; }
 . $HOME/.config/galley
 
 # We ignore the output of the create command because it sometimes returns
@@ -13,16 +14,18 @@
 # We sleep before getting the IP address as it doesn't slow things down
 # and gives Digital Ocean a little more time to ascertain the correct IP
 # address.
-echo "# Creating droplet"
-doctl compute droplet create --region $G_REGION --image $G_IMAGE --size $G_SIZE --ssh-keys $G_KEY --wait $G_HOST > /dev/null
+echo "# Creating droplet $G_IMAGE $G_SIZE $G_HOST"
+doctl compute droplet create --region $G_REGION --image $G_IMAGE \
+    --size $G_SIZE --ssh-keys $G_KEY --wait $G_HOST > /dev/null
 
 echo "# Waiting $G_SLEEP seconds for droplet to be ready..."
 sleep $G_SLEEP
 
-echo "# Finding IP address"
+printf '%s' "# Finding IP address"
 G_IP=`doctl compute droplet list | grep $G_HOST | awk '{ print $3 }'`
+echo ": $G_IP"
 
-# Connect quietly and skip strict key checking as Digital Ocean reuses IP addresses
+# Connect quietly and skip strict key because IP address reuse
 GS="ssh -q -o StrictHostKeyChecking=no root@$G_IP"
 
 echo "# Suppressing login messages for interactive sessions and creating build directory"
